# ECT_HW3_Part2
### 1

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('customer_churn.csv')
df

CustomerID  Churn  Tenure PreferredLoginDevice  CityTier  \
0          54023      1     1.0             Computer         1   
1          50266      0    16.0         Mobile Phone         1   
2          54985      0    16.0         Mobile Phone         1   
3          52029      1     0.0                Phone         3   
4          50084      0    13.0             Computer         1   
5          52379      1     0.0             Computer         1   
6          54025      0     1.0             Computer         1   
7          50545      1     2.0                Phone         1   
8          51280      0    15.0             Computer         1   
9          55246      1     1.0             Computer         1   
10         53159      0    26.0         Mobile Phone         1   
11         51073      0     0.0                Phone         3   
12         53988      1     1.0                Phone         2   
13         53450      0    19.0                Phone         2   
14         54769      1    19.0         Mobile Phone         3   
15         50329      1     0.0             Computer         2   
16         50311      1     0.0         Mobile Phone         1   
17         51881      0    14.0         Mobile Phone         2   
18         52789      0    15.0         Mobile Phone         1   
19         52027      0    11.0         Mobile Phone         1   
20         52475      0    15.0         Mobile Phone         1   
21         54153      0    13.0         Mobile Phone         3   
22         54104      0     1.0         Mobile Phone         1   
23         51128      0     7.0                Phone         1   
24         55357      0    15.0         Mobile Phone         3   
25         51146      0     7.0         Mobile Phone         3   
26         53835      0     5.0             Computer         3   
27         52451      0     6.0         Mobile Phone         3   
28         52391      0    13.0                Phone         1   
29         54303      0    12.0         Mobile Phone         1   
...          ...    ...     ...                  ...       ...   
3053       50946      0     1.0             Computer         3   
3054       55028      0    24.0             Computer         1   
3055       50357      0     7.0                Phone         1   
3056       52580      0    20.0             Computer         3   
3057       53838      0    23.0         Mobile Phone         1   
3058       52724      0    15.0         Mobile Phone         3   
3059       54380      0    28.0         Mobile Phone         3   
3060       51922      0     0.0             Computer         3   
3061       50586      0     6.0             Computer         3   
3062       54514      0    11.0         Mobile Phone         1   
3063       52395      0     3.0         Mobile Phone         3   
3064       54990      1     1.0         Mobile Phone         3   
3065       50003      1     NaN                Phone         1   
3066       53348      0     3.0         Mobile Phone         1   
3067       53475      0    12.0         Mobile Phone         1   
3068       53636      0    24.0         Mobile Phone         1   
3069       50410      0    26.0         Mobile Phone         1   
3070       52790      1    19.0                Phone         1   
3071       53666      1    19.0         Mobile Phone         3   
3072       55159      0     1.0         Mobile Phone         1   
3073       52009      1     0.0                Phone         1   
3074       51520      0    18.0         Mobile Phone         3   
3075       51261      0     7.0         Mobile Phone         3   
3076       54400      1     1.0         Mobile Phone         1   
3077       53640      0    13.0         Mobile Phone         1   
3078       51224      0    13.0         Mobile Phone         1   
3079       51396      1    11.0         Mobile Phone         1   
3080       52017      0     NaN         Mobile Phone         1   
3081       50355      1     0.0             Co

### 2

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3083 entries, 0 to 3082
Data columns (total 20 columns):
CustomerID                     3083 non-null int64
Churn                          3083 non-null int64
Tenure                         2930 non-null float64
PreferredLoginDevice           3083 non-null object
CityTier                       3083 non-null int64
WarehouseToHome                2929 non-null float64
PreferredPaymentMode           3083 non-null object
Gender                         3083 non-null object
HourSpendOnApp                 2933 non-null float64
NumberOfDeviceRegistered       3083 non-null int64
PreferedOrderCat               3083 non-null object
SatisfactionScore              3083 non-null int64
MaritalStatus                  3083 non-null object
NumberOfAddress                3083 non-null int64
Complain                       3083 non-null int64
OrderAmountHikeFromlastYear    2952 non-null float64
CouponUsed                     2957 non-null float64
OrderCount 

由上可知：<br>
資料筆數：3083<br>
屬性數量 : 20<br>
各類別資料筆數寫在第二列（3083,3083,2930,3083,...,2917,3083)

In [3]:
print("各欄位空值數量：")
df.isnull().sum()

各欄位空值數量：


CustomerID                       0
Churn                            0
Tenure                         153
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                154
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 150
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    131
CouponUsed                     126
OrderCount                     128
DaySinceLastOrder              166
CashbackAmount                   0
dtype: int64

### 3

In [4]:
df[df.duplicated()]

CustomerID  Churn  Tenure PreferredLoginDevice  CityTier  \
1220       50180      0    12.0         Mobile Phone         1   
2100       50135      1     0.0             Computer         1   
2769       50135      1     0.0             Computer         1   
2846       50081      1     0.0         Mobile Phone         3   
2935       50180      0    12.0         Mobile Phone         1   

      WarehouseToHome PreferredPaymentMode  Gender  HourSpendOnApp  \
1220              6.0          Credit Card    Male             2.0   
2100             35.0                   CC    Male             3.0   
2769             35.0                   CC    Male             3.0   
2846             33.0             E wallet  Female             2.0   
2935              6.0          Credit Card    Male             2.0   

      NumberOfDeviceRegistered PreferedOrderCat  SatisfactionScore  \
1220                         2          Fashion                  2   
2100                         4           Mobile                  4   
2769                         4           Mobile                  4   
2846                         3          Fashion                  2   
2935                         2          Fashion                  2   

     MaritalStatus  NumberOfAddress  Complain  OrderAmountHikeFromlastYear  \
1220       Married                1         0                         17.0   
2100        Single                1         0                         11.0   
2769        Single                1         0                         11.0   
2846      Divorced                2         0                         22.0   
2935       Married                1         0                         17.0   

      CouponUsed  OrderCount  DaySinceLastOrder  CashbackAmount  
1220         3.0         3.0                7.0             196  
2100         1.0         1.0                4.0             135  
2769         1.0         1.0                4.0             135  
2846         1.0         1.0                9.0             176  
2935         3.0         3.0                7.0             196

In [5]:
column_names = ['CustomerID', 'Churn', 'Tenure', 'PreferredLoginDevice', 'CityTier', 'WarehouseToHome', 'PreferredPaymentMode', 'Gender', 'HourSpendOnApp', 'NumberOfDeviceRegistered']
 
df.drop_duplicates(subset=column_names, keep='first', inplace=True)

In [6]:
df.info()
print('\n刪除重複資料後筆數：',len(df))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3078 entries, 0 to 3082
Data columns (total 20 columns):
CustomerID                     3078 non-null int64
Churn                          3078 non-null int64
Tenure                         2925 non-null float64
PreferredLoginDevice           3078 non-null object
CityTier                       3078 non-null int64
WarehouseToHome                2924 non-null float64
PreferredPaymentMode           3078 non-null object
Gender                         3078 non-null object
HourSpendOnApp                 2928 non-null float64
NumberOfDeviceRegistered       3078 non-null int64
PreferedOrderCat               3078 non-null object
SatisfactionScore              3078 non-null int64
MaritalStatus                  3078 non-null object
NumberOfAddress                3078 non-null int64
Complain                       3078 non-null int64
OrderAmountHikeFromlastYear    2947 non-null float64
CouponUsed                     2952 non-null float64
OrderCount 

### 4

In [7]:
df.isnull()

CustomerID  Churn  Tenure  PreferredLoginDevice  CityTier  \
0          False  False   False                 False     False   
1          False  False   False                 False     False   
2          False  False   False                 False     False   
3          False  False   False                 False     False   
4          False  False   False                 False     False   
5          False  False   False                 False     False   
6          False  False   False                 False     False   
7          False  False   False                 False     False   
8          False  False   False                 False     False   
9          False  False   False                 False     False   
10         False  False   False                 False     False   
11         False  False   False                 False     False   
12         False  False   False                 False     False   
13         False  False   False                 False     False   
14         False  False   False                 False     False   
15         False  False   False                 False     False   
16         False  False   False                 False     False   
17         False  False   False                 False     False   
18         False  False   False                 False     False   
19         False  False   False                 False     False   
20         False  False   False                 False     False   
21         False  False   False                 False     False   
22         False  False   False                 False     False   
23         False  False   False                 False     False   
24         False  False   False                 False     False   
25         False  False   False                 False     False   
26         False  False   False                 False     False   
27         False  False   False                 False     False   
28         False  False   False                 False     False   
29         False  False   False                 False     False   
...          ...    ...     ...                   ...       ...   
3053       False  False   False                 False     False   
3054       False  False   False                 False     False   
3055       False  False   False                 False     False   
3056       False  False   False                 False     False   
3057       False  False   False                 False     False   
3058       False  False   False                 False     False   
3059       False  False   False                 False     False   
3060       False  False   False                 False     False   
3061       False  False   False                 False     False   
3062       False  False   False                 False     False   
3063       False  False   False                 False     False   
3064       False  False   False                 False     False   
3065       False  False    True                 False     False   
3066       False  False   False                 False     False   
3067       False  False   False                 False     False   
3068       False  False   False                 False     False   
3069       False  False   False                 False     False   
3070       False  False   False                 False     False   
3071       False  False   False                 False     False   
3072       False  False   False                 False     False   
3073       False  False   False                 False     False   
3074       False  False   False                 False     False   
3075       False  False   False                 False     False   
3076       False  False   False                 False     False   
3077       False  False   False                 False     False   
3078       False  False   False                 False     False   
3079       False  False   False                 False     False   
3080       False  False    True                 False

In [8]:
df.groupby(['PreferredLoginDevice']).size()

PreferredLoginDevice
Computer         926
Mobile Phone    1455
Phone            697
dtype: int64

In [9]:
df.groupby(['PreferredPaymentMode']).size()

PreferredPaymentMode
CC                   145
COD                  225
Cash on Delivery      77
Credit Card          787
Debit Card          1255
E wallet             367
UPI                  222
dtype: int64

In [10]:
df.groupby(['Gender']).size()

Gender
Female    1228
Male      1850
dtype: int64

In [11]:
df.groupby(['PreferedOrderCat']).size()

PreferedOrderCat
Fashion                446
Grocery                198
Laptop & Accessory    1066
Mobile                 461
Mobile Phone           772
Others                 135
dtype: int64

In [12]:
df.groupby(['MaritalStatus']).size()

MaritalStatus
Divorced     433
Married     1545
Single      1100
dtype: int64

In [13]:
#將字串轉換成數字分類

#PreferredLoginDevice部分
df.loc[df.PreferredLoginDevice == 'Computer', 'PreferredLoginDevice'] = 0
df.loc[df.PreferredLoginDevice == 'Mobile Phone', 'PreferredLoginDevice'] = 1
df.loc[df.PreferredLoginDevice == 'Phone', 'PreferredLoginDevice'] = 2

#PreferredPaymentMode部分
df.loc[df.PreferredPaymentMode == 'CC', 'PreferredPaymentMode'] = 0
df.loc[df.PreferredPaymentMode == 'COD', 'PreferredPaymentMode'] = 1
df.loc[df.PreferredPaymentMode == 'Cash on Delivery', 'PreferredPaymentMode'] = 2
df.loc[df.PreferredPaymentMode == 'Credit Card', 'PreferredPaymentMode'] = 3
df.loc[df.PreferredPaymentMode == 'Debit Card', 'PreferredPaymentMode'] = 4
df.loc[df.PreferredPaymentMode == 'E wallet', 'PreferredPaymentMode'] = 5
df.loc[df.PreferredPaymentMode == 'UPI', 'PreferredPaymentMode'] = 6

#Gender部分
df.loc[df.Gender == 'Male', 'Gender'] = 0
df.loc[df.Gender == 'Female', 'Gender'] = 1

#PreferedOrderCat部分
df.loc[df.PreferedOrderCat == 'Fashion', 'PreferedOrderCat'] = 0
df.loc[df.PreferedOrderCat == 'Grocery', 'PreferedOrderCat'] = 1
df.loc[df.PreferedOrderCat == 'Laptop & Accessory', 'PreferedOrderCat'] = 2
df.loc[df.PreferedOrderCat == 'Mobile', 'PreferedOrderCat'] = 3
df.loc[df.PreferedOrderCat == 'Mobile Phone', 'PreferedOrderCat'] = 4
df.loc[df.PreferedOrderCat == 'Others', 'PreferedOrderCat'] = 5

#MaritalStatus部分
df.loc[df.MaritalStatus == 'Divorced', 'MaritalStatus'] = 0
df.loc[df.MaritalStatus == 'Married', 'MaritalStatus'] = 1
df.loc[df.MaritalStatus == 'Single', 'MaritalStatus'] = 2

df

CustomerID  Churn  Tenure  PreferredLoginDevice  CityTier  \
0          54023      1     1.0                     0         1   
1          50266      0    16.0                     1         1   
2          54985      0    16.0                     1         1   
3          52029      1     0.0                     2         3   
4          50084      0    13.0                     0         1   
5          52379      1     0.0                     0         1   
6          54025      0     1.0                     0         1   
7          50545      1     2.0                     2         1   
8          51280      0    15.0                     0         1   
9          55246      1     1.0                     0         1   
10         53159      0    26.0                     1         1   
11         51073      0     0.0                     2         3   
12         53988      1     1.0                     2         2   
13         53450      0    19.0                     2         2   
14         54769      1    19.0                     1         3   
15         50329      1     0.0                     0         2   
16         50311      1     0.0                     1         1   
17         51881      0    14.0                     1         2   
18         52789      0    15.0                     1         1   
19         52027      0    11.0                     1         1   
20         52475      0    15.0                     1         1   
21         54153      0    13.0                     1         3   
22         54104      0     1.0                     1         1   
23         51128      0     7.0                     2         1   
24         55357      0    15.0                     1         3   
25         51146      0     7.0                     1         3   
26         53835      0     5.0                     0         3   
27         52451      0     6.0                     1         3   
28         52391      0    13.0                     2         1   
29         54303      0    12.0                     1         1   
...          ...    ...     ...                   ...       ...   
3053       50946      0     1.0                     0         3   
3054       55028      0    24.0                     0         1   
3055       50357      0     7.0                     2         1   
3056       52580      0    20.0                     0         3   
3057       53838      0    23.0                     1         1   
3058       52724      0    15.0                     1         3   
3059       54380      0    28.0                     1         3   
3060       51922      0     0.0                     0         3   
3061       50586      0     6.0                     0         3   
3062       54514      0    11.0                     1         1   
3063       52395      0     3.0                     1         3   
3064       54990      1     1.0                     1         3   
3065       50003      1     NaN                     2         1   
3066       53348      0     3.0                     1         1   
3067       53475      0    12.0                     1         1   
3068       53636      0    24.0                     1         1   
3069       50410      0    26.0                     1         1   
3070       52790      1    19.0                     2         1   
3071       53666      1    19.0                     1         3   
3072       55159      0     1.0                     1         1   
3073       52009      1     0.0                     2         1   
3074       51520      0    18.0                     1         3   
3075       51261      0     7.0                     1         3   
3076       54400      1     1.0                     1         1   
3077       53640      0    13.0                     1         1   
3078       51224      0    13.0                     1         1   
3079       51396      1    11.0                     1         1   
3080       52017      0     NaN                     1

In [14]:
#空值部分直接以平均數帶入
df.fillna(df.mean(),inplace=True)
df

CustomerID  Churn     Tenure  PreferredLoginDevice  CityTier  \
0          54023      1   1.000000                     0         1   
1          50266      0  16.000000                     1         1   
2          54985      0  16.000000                     1         1   
3          52029      1   0.000000                     2         3   
4          50084      0  13.000000                     0         1   
5          52379      1   0.000000                     0         1   
6          54025      0   1.000000                     0         1   
7          50545      1   2.000000                     2         1   
8          51280      0  15.000000                     0         1   
9          55246      1   1.000000                     0         1   
10         53159      0  26.000000                     1         1   
11         51073      0   0.000000                     2         3   
12         53988      1   1.000000                     2         2   
13         53450      0  19.000000                     2         2   
14         54769      1  19.000000                     1         3   
15         50329      1   0.000000                     0         2   
16         50311      1   0.000000                     1         1   
17         51881      0  14.000000                     1         2   
18         52789      0  15.000000                     1         1   
19         52027      0  11.000000                     1         1   
20         52475      0  15.000000                     1         1   
21         54153      0  13.000000                     1         3   
22         54104      0   1.000000                     1         1   
23         51128      0   7.000000                     2         1   
24         55357      0  15.000000                     1         3   
25         51146      0   7.000000                     1         3   
26         53835      0   5.000000                     0         3   
27         52451      0   6.000000                     1         3   
28         52391      0  13.000000                     2         1   
29         54303      0  12.000000                     1         1   
...          ...    ...        ...                   ...       ...   
3053       50946      0   1.000000                     0         3   
3054       55028      0  24.000000                     0         1   
3055       50357      0   7.000000                     2         1   
3056       52580      0  20.000000                     0         3   
3057       53838      0  23.000000                     1         1   
3058       52724      0  15.000000                     1         3   
3059       54380      0  28.000000                     1         3   
3060       51922      0   0.000000                     0         3   
3061       50586      0   6.000000                     0         3   
3062       54514      0  11.000000                     1         1   
3063       52395      0   3.000000                     1         3   
3064       54990      1   1.000000                     1         3   
3065       50003      1   9.115897                     2         1   
3066       53348      0   3.000000                     1         1   
3067       53475      0  12.000000                     1         1   
3068       53636      0  24.000000                     1         1   
3069       50410      0  26.000000                     1         1   
3070       52790      1  19.000000                     2         1   
3071       53666      1  19.000000                     1         3   
3072       55159      0   1.000000                     1         1   
3073       52009      1   0.000000                     2         1   
3074       51520      0  18.000000                     1         3   
3075       51261      0   7.000000                     1         3   
3076       54400      1   1.000000                     1         1   
3077       53640      0  13.000000                     1         1   
3078       51224

### 5

In [15]:
from sklearn import tree
from sklearn.linear_model import LinearRegression
from sklearn import svm
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import export_graphviz
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


X = df.drop(['Churn'], axis = 1)
y = df['Churn']#要預測的欄位

X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.5, random_state = 12)

### 6,7
SVM部分

In [16]:
#kernel = linear
svmModel = svm.SVR(C=1,kernel='linear') 
svmModel.fit(X_train, y_train)

SVR(C=1, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
svmscore = svmModel.score(X_test, y_test)
print('coefficient of determination:', svmscore)

coefficient of determination: -715957.1961205789


In [18]:
ys_pred = svmModel.predict(X_test)
print('Predicted response:', ys_pred, sep='\n')

Predicted response:
[ -93.04866696  387.70029544 -302.37813473 ... -175.6101656   333.95785426
 -171.5196085 ]


In [19]:
#### kernel = rbf
rbfModel = svm.SVR(C=6,kernel='rbf',degree=3,gamma='auto') 
rbfModel.fit(X_train, y_train)

SVR(C=6, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [20]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
rbfscore = rbfModel.score(X_test, y_test)
print('coefficient of determination:', rbfscore)

coefficient of determination: -0.003969481298049526


In [21]:
ysr_pred = rbfModel.predict(X_test)
print('Predicted response:', ysr_pred, sep='\n')

Predicted response:
[0.34361039 0.34318486 0.34316736 ... 0.34319898 0.34319898 0.34319865]


In [33]:
svcModel = svm.LinearSVC(C=1, max_iter=10000) 
svcModel.fit(X_train, y_train)

/Users/brian/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=10000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [34]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
cscore = svcModel.score(X_test, y_test)
print('coefficient of determination:', cscore)

coefficient of determination: 0.6887589343729694


In [35]:
ysvc_pred = svcModel.predict(X_test)
print('Predicted response:', ysvc_pred, sep='\n')

Predicted response:
[0 0 0 ... 0 0 0]


In [25]:
crbfModel=svm.SVC(kernel='rbf', gamma=0.7, C=1)
crbfModel.fit(X_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.7, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
crscore = crbfModel.score(X_test, y_test)
print('coefficient of determination:', crscore)

coefficient of determination: 0.6887589343729694


In [36]:
Model=svm.SVC(kernel='linear',C=1)
Model.fit(X_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [37]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
score = Model.score(X_test, y_test)
print('coefficient of determination:', score)

coefficient of determination: 0.8050682261208577


最後選擇此SVM模型 accuracy最高

In [38]:
y_pred = Model.predict(X_test)
print('Predicted response:', y_pred, sep='\n')

Predicted response:
[0 0 1 ... 1 0 1]


Logistic Regression部分

In [27]:
from sklearn.linear_model import LogisticRegression

lmodel = LogisticRegression()
lmodel.fit(X_train, y_train)

/Users/brian/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
lscore = lmodel.score(X_test, y_test)
print('coefficient of determination:', lscore)

coefficient of determination: 0.7992202729044834


In [29]:
yl_pred = lmodel.predict(X_test)
print('Predicted response:', yl_pred, sep='\n')

Predicted response:
[0 0 0 ... 1 0 1]


Decision Tree部分

In [30]:
from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier(criterion='gini')
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [31]:
# Obtain the coefficient of determination by calling the model with the score() function, then print the coefficient:
dtscore = dtree.score(X_test, y_test)
print('coefficient of determination:', dtscore)

coefficient of determination: 0.8687459389213775


In [32]:
ydt_pred = dtree.predict(X_test)
print('Predicted response:', ydt_pred, sep='\n')

Predicted response:
[1 0 1 ... 1 0 1]


### 8

In [45]:
svcaccuracy = accuracy_score(y_test, y_pred)
lraccuracy = accuracy_score(y_test, yl_pred)
dtaccuracy = accuracy_score(y_test, ydt_pred)

print("SVM accuracy: ", svcaccuracy,"\nLogistic Regression accuracy: ", lraccuracy,"\nDecision Tree accuracy:", dtaccuracy)

SVM accuracy:  0.8050682261208577 
Logistic Regression accuracy:  0.7992202729044834 
Decision Tree accuracy: 0.8687459389213775


### 9

In [48]:
svccm = confusion_matrix(y_test, y_pred)
lrcm = confusion_matrix(y_test, yl_pred)
dtcm = confusion_matrix(y_test, ydt_pred)


print("SVM confusion matrix: \n", svccm,"\nLogistic Regression confusion matrix: \n", lrcm, "\nDecision Tree confusion matrix: \n", dtcm)

SVM confusion matrix: 
 [[1009   51]
 [ 249  230]] 
Logistic Regression confusion matrix: 
 [[964  96]
 [213 266]] 
Decision Tree confusion matrix: 
 [[956 104]
 [ 98 381]]


[預測為真實際為真(TP) 預測為真實際為假(FN)]<br>
[預測為假實際為真(FP) 預測為假實際為假(TN)]

TP+TN為所有預測中正確的<br>
TP+TN/TP+FN+FP+TN 表示Accuracy表全部中預測正確的比例